// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMvZb61BBhRWcKARJ_o1HA1Va2b-ezKvU',
    appId: '1:135440391064:web:c134f8f5ca6c61212d29ed',
    messagingSenderId: '135440391064',
    projectId: 'app-kahoot',
    authDomain: 'app-kahoot.firebaseapp.com',
    storageBucket: 'app-kahoot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGst-y1aWEjYEmsuC4y3y6d5XhFbNu7Ic',
    appId: '1:135440391064:android:477f5d49d4bc71f92d29ed',
    messagingSenderId: '135440391064',
    projectId: 'app-kahoot',
    storageBucket: 'app-kahoot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC88XNasTsmfyRZ1mXiRnJDlnyS6_KlCIU',
    appId: '1:135440391064:ios:168a4b73902357b32d29ed',
    messagingSenderId: '135440391064',
    projectId: 'app-kahoot',
    storageBucket: 'app-kahoot.firebasestorage.app',
    iosBundleId: 'com.tunombre.kahoot.appKahoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC88XNasTsmfyRZ1mXiRnJDlnyS6_KlCIU',
    appId: '1:135440391064:ios:168a4b73902357b32d29ed',
    messagingSenderId: '135440391064',
    projectId: 'app-kahoot',
    storageBucket: 'app-kahoot.firebasestorage.app',
    iosBundleId: 'com.tunombre.kahoot.appKahoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMvZb61BBhRWcKARJ_o1HA1Va2b-ezKvU',
    appId: '1:135440391064:web:9b165f9dcfef6cdb2d29ed',
    messagingSenderId: '135440391064',
    projectId: 'app-kahoot',
    authDomain: 'app-kahoot.firebaseapp.com',
    storageBucket: 'app-kahoot.firebasestorage.app',
  );
}
